### ISSUE TITLE
Missed MIDI notes (MIDI out)

### ISSUE THREAD

**Issue by nervousapps** [BenZonneveld/Nava-v1.0-code#36]
When sending midi out of Nava (in SLAVE mode) to PC/DAW some notes are missing. I do not know if there are some settings to tweak for this to work perfectly.

I did not test that in MASTER mode.

**Comment by BenZonneveld** [comment]
This was caused by me not noticing the velocity for accented notes was wrong. Fixed this.

**Comment by BenZonneveld** [comment]
Solved in the latest beta build
