### ISSUE TITLE
Config changes can't be saved

### ISSUE THREAD

**Issue by williamdcole** [BenZonneveld/Nava-v1.0-code#37]
To reproduce:
1. boot Nava
2. change midi Tx, Rx, boot mode, etc
3. Tap Enter button (button NOT flashing)
4. reboot Nava
5. View config. Changes from Step 2 not shown.

**Comment by BenZonneveld** [comment]
I just noticed this, looking into it now.

**Comment by BenZonneveld** [comment]
Fixed in the current source
