### ISSUE TITLE
Pattern group not working correctly

### ISSUE THREAD

**Issue by williamdcole** [BenZonneveld/Nava-v1.0-code#41]
Steps to reproduce:

1 Activate Pattern Play mode
2. Select a pattern group (hold down a step button and press another step button to its right)
3. Play pattern group

Expected: All patterns in group play sequentially
Actual behavior: First pattern (left) plays once. Second pattern plays and repeats. Subsequent patterns in the loop are not played. Also, upon selecting a completely different group of patterns, the second pattern from the _original_ group continues to repeat. User must select a _single_ pattern _not in the current group_ to resume normal playback.

**Comment by BenZonneveld** [comment]
Should be fixed in the Nava2021Beta december 2021 release
